### ISSUE TITLE
Running failed

### ISSUE THREAD

**Issue by tchukuchuk** [maccman/bowline-twitter#1]
Hi,

I have had this issue when I try to run the application :
-> script/run 
    uninitialized constant Twitter
/Users/jbiard/dev/bowline-twitter/app/models/tweet.rb:26:in `twitter'
    /Users/jbiard/dev/bowline-twitter/app/models/tweet.rb:18:in`timeline'
    /Users/jbiard/dev/bowline-twitter/app/models/tweet.rb:6:in `poll'
    /Users/jbiard/dev/bowline-twitter/config/initializers/tweet.rb:1:in`<top (required)>'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/initializer.rb:235:in `block in load_application_initializers'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/initializer.rb:234:in`each'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/initializer.rb:234:in `load_application_initializers'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/initializer.rb:372:in`process'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/initializer.rb:70:in `run'
    /Users/jbiard/dev/bowline-twitter/config/environment.rb:4:in`<top (required)>'
    /Users/jbiard/dev/bowline-twitter/script/init:2:in `require'

So, I have added require 'twitter' at the first line of tweet.rb , and now I have this issue :

-> script/run 
    dlopen(/Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/yajl-ruby-0.7.6/ext/yajl_ext.bundle, 9): no suitable image found.  Did find:
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/yajl-ruby-0.7.6/ext/yajl_ext.bundle: mach-o, but wrong architecture - /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/yajl-ruby-0.7.6/ext/yajl_ext.bundle
/Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in `require'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in`block in require'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:197:in `load_dependency'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in`require'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/yajl-ruby-0.7.6/lib/yajl.rb:2:in `<top (required)>'

I don't understand because I have no problem in irb :

ruby-1.9.1-p378 > require 'twitter'
 => true

In the meantime, I can't launch bowline-gen :

-> bowline-gen --help
/Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/generators/application.rb:67:in `<class:ApplicationGenerator>': wrong number of arguments (1 for 2) (ArgumentError)
    from /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/generators/application.rb:2:in`module:Generators'
    from /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bowline-0.6.3/lib/bowline/generators/application.rb:1:in `<top (required)>'
    from /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in`require'
    from /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:209:in `block in require'
    from /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/activesupport-3.0.0.beta3/lib/active_support/dependencies.rb:195:in`block in load_dependency'

I am very interested by Bowline, but I am so disappointed to not be abble to use your gem.

Best regards,

Julien

**Comment by maccman** [comment]
I'm pretty sure the solution to your problems is to run:
gem bundle

Make sure you're using Ruby 1.9 too. The second issue is that bowline's Ruby is compiled in 32 bit mode, not 64. Running gem bundle should solve this too.

Hmm, not sure about the third issue. Can you pull from master and see if you still get that problem?

**Comment by tchukuchuk** [comment]
Which version of bundler I have to use ? Because with the 0.9.25 I have :

-> gem bundle
ERROR:  While executing gem ... (RuntimeError)
    Unknown command bundle

With the last version available on GitHub, it seems working :

jbiard@stick - [1.9.1p378] - (master) - ~/dev/bowline -
-> bin/bowline-gen 
Usage: bowline generator_name [options] [args]

Generate components for your application or entirely new applications.

Available generators
    app                              Generates a new application.
    binder                           Generates a new binder.
    helper                           Generates a new helper.
    migration                        Generates a new database migration.
    model                            Generates a new model.
    window                           Generates a new window.

General options:
    -p, --pretend                    Run, but do not make any changes.
    -f, --force                      Overwrite files that already exist.
    -s, --skip                       Skip files that already exist.
    -d, --delete                     Delete files that have previously been generated with this generator.
        --no-color                   Don't colorize the output
    -h, --help                       Show this message
        --debug                      Do not catch errors

Thanks for your help.

**Comment by maccman** [comment]
Ok, sorry, I forgot to push the gem to gemcutter. The latest released gem should now be in sync with the github master branch.

You need to install bundler08 - which I think is a gemspec dependency for bowline.

**Comment by tchukuchuk** [comment]
Ok, I have updated bowline.

But I still have issues :

-> gem bundle

Calculating dependencies...
Updating source: http://rubygems.org
Updating source: http://gems.rubyforge.org
/Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:115:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
Caching: activemodel-3.0.0.beta3.gem
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/cache/activemodel-3.0.0.beta3.gem

After cleaning my gem cache directory, I have :

-> gem bundle 

Calculating dependencies...
ERROR:  While executing gem ... (NoMethodError)
    undefined method `spec' for nil:NilClass

**Comment by maccman** [comment]
ok, try this:
cd to bowline-twitter
rm -rf vendor/cache
rm -rf vendor/gems
rm -rf .bundle

Then try updating your RubyGems.

**Comment by maccman** [comment]
You could try to uninstall bundler (not bundler08) - just to see if the two are conflicting.

also, what's the backtrace of gem bundle?

**Comment by maccman** [comment]
Ignore everything I said above - I've found the issue. Give me a couple of mins.

**Comment by maccman** [comment]
Ok, hopefully the update to boot.rb has fixed your problems. Let me know if it hasn't.

**Comment by tchukuchuk** [comment]
-> gem bundle 

Calculating dependencies...
Updating source: http://rubygems.org
Updating source: http://gems.rubyforge.org
/Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:115:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
Caching: activemodel-3.0.0.beta3.gem
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/cache/activemodel-3.0.0.beta3.gem

-> gem bundle --backtrace

Calculating dependencies...
ERROR:  While executing gem ... (NoMethodError)
    undefined method `spec' for nil:NilClass
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/source.rb:177:in`block in fetch_specs'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/source.rb:176:in `each'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/source.rb:176:in`fetch_specs'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/source.rb:156:in `gems'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:86:in`block in initialize'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:85:in `each'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:85:in`initialize'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:47:in `new'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/resolver.rb:47:in`resolve'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/bundle.rb:93:in `install'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/cli.rb:40:in`bundle'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/cli.rb:85:in `run'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/cli.rb:6:in`run'
    /Users/jbiard/.rvm/gems/ruby-1.9.1-p378/gems/bundler08-0.8.5/lib/bundler08/commands/bundle_command.rb:80:in `execute'
    /Users/jbiard/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/site_ruby/1.9.1/rubygems/command.rb:270:in`invoke'
    /Users/jbiard/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/site_ruby/1.9.1/rubygems/command_manager.rb:134:in `process_args'
    /Users/jbiard/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/site_ruby/1.9.1/rubygems/command_manager.rb:104:in`run'
    /Users/jbiard/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/site_ruby/1.9.1/rubygems/gem_runner.rb:58:in `run'
    /Users/jbiard/.rvm/rubies/ruby-1.9.1-p378/bin/gem:29:in`<main>'

**Comment by tchukuchuk** [comment]
Have you checked my last error ?
Thanks,

**Comment by maccman** [comment]
Ok, this should be sorted now. Use the gem 'bowline-bundler' and execute bowline-bundle instead of gem bundle.
