### ISSUE TITLE
Bundler 0.9.26 on Ruby 1.9.2-preview3 misses tzinfo.

### ISSUE THREAD

**Issue by postmodern** [maccman/bowline-twitter#2]
Since bowline requires ActiveSupport 3.0.0.beta4, it also requires tzinfo. For some reason Bundler 0.9.26 seems to not automatically bundle in tzinfo. After adding `gem "tzinfo"` to the Gemfile, ActiveSupport was able to be loaded by Bowline.

**Comment by maccman** [comment]
Thanks, fixed.
